### ISSUE TITLE
Cards' height not equal

### ISSUE THREAD

**Issue by sumilmehta** [UdacityFrontEndScholarship/jeevan-rakht#174]
The blood needed cards are not of equal sizes
![capture](https://user-images.githubusercontent.com/18137211/39661327-341b2228-506d-11e8-87bc-b2b4052c8b50.JPG)

**Comment by abhishekakade** [comment]
That's because of the content inside it. I've used Bootstrap and kept the height to auto since the content inside those cards won't be the same for all the cards in real use anyways. If they want to keep the height fixed just for that then we can hide the overflow but that will defeat the whole purpose of the card I think.

**Comment by utkarsh2102** [comment]
The website is being redesigned now.
Thank you for noticing details very minutely. 
Please help us in rebuilding the site now.
