### ISSUE TITLE
Unable to run it offline using gulp command.

### ISSUE THREAD

**Issue by adsingh14** [UdacityFrontEndScholarship/jeevan-rakht#187]
Hi! 
I just found that this project isn't working offline properly using `gulp` command.

How to run this project :
- Terminate the `gulp` command(if you've execute it).
- Start nodemon by `npm start` -> then type `localhost:3000` manually in your web browser's address bar.

Now the problem is, what is the real use of `gulp` command if it takes us to blank page having git-logo on the top-right corner?

**Comment by mohit94614** [comment]
The project is executing the thing is that the page that's is opening by `gulp` is blank by itself such that it;s under development process .
 Run the project under `npm start ` That is the working project

**Comment by gauravsinghaec** [comment]
There has been notice that we are redesigning our website. Also you might check that index.html is website page which is blank now. So the gulp is opening the index.html file and it is expected. I think it is clearly mentioned that no start is for app and which is why you are getting the content. So if you are interested in working on Frontend website page then yes gulp will help you and as soon as the index.html gets it's content the gulp command won't disappoint you. :-)
