### ISSUE TITLE
Why Mobile Number field is readonly? Not able to add the number

### ISSUE THREAD

**Issue by mmnauman** [UdacityFrontEndScholarship/jeevan-rakht#192]
Hello, When I was debugging the profile section an I found that the mobile number field is readonly and cannot be edited.

![mobile number disabled](https://user-images.githubusercontent.com/23205151/39735846-1ddc7090-529b-11e8-80e4-964e30694002.JPG)
![this field is disabled](https://user-images.githubusercontent.com/23205151/39735847-1e1d7004-529b-11e8-9cda-f3799b7633da.JPG)

**Comment by gauravsinghaec** [comment]
@mmnauman Thanks for your time on validation. The mobile number and email can't be edited as we want only verified num/email to be added. Once we add the OTP verification functionality, you will be able to see mobile and it will be captured via signup. Bear with us till then and yeah we would love to see you coming up with pseudo code for OTP verification. If you already have then do share the link so that we can implement it in next scope. 
Check below 3rd party API for SMS service but it allows sms to be sent only to verified number in free tier.
https://www.twilio.com/

**Comment by gauravsinghaec** [comment]
This will get reflected in our next deployment. Thanks @mmnauman 💯
